// <auto-generated />
using System;
using DersProje.Models.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DersProje.Migrations
{
    [DbContext(typeof(DersProjeDbContext))]
    partial class DersProjeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.16");

            modelBuilder.Entity("DersProje.Models.Entity.Bolum", b =>
                {
                    b.Property<int>("BolumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BolumAd")
                        .HasColumnType("TEXT");

                    b.Property<string>("BolumBaskani")
                        .HasColumnType("TEXT");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BolumId");

                    b.HasIndex("OgrenciId")
                        .IsUnique();

                    b.ToTable("Bolumler");
                });

            modelBuilder.Entity("DersProje.Models.Entity.Ders", b =>
                {
                    b.Property<int>("DersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DersAdi")
                        .HasColumnType("TEXT");

                    b.Property<string>("DersOgretmeni")
                        .HasColumnType("TEXT");

                    b.Property<int>("Donemi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kredi")
                        .HasColumnType("INTEGER");

                    b.HasKey("DersId");

                    b.ToTable("Dersler");
                });

            modelBuilder.Entity("DersProje.Models.Entity.Ogrenci", b =>
                {
                    b.Property<int>("OgrenciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("Donemi")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("OgrenciBolumId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OgrenciIsmi")
                        .HasColumnType("TEXT");

                    b.Property<int>("OgrenciNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OgrenciSoyad")
                        .HasColumnType("TEXT");

                    b.HasKey("OgrenciId");

                    b.ToTable("Ogrenciler");
                });

            modelBuilder.Entity("DersProje.Models.Entity.OgrenciDers", b =>
                {
                    b.Property<int>("OgrenciDersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DersId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OgrenciDersId");

                    b.HasIndex("DersId");

                    b.HasIndex("OgrenciId");

                    b.ToTable("OgrenciDersler");
                });

            modelBuilder.Entity("DersProje.Models.Entity.Bolum", b =>
                {
                    b.HasOne("DersProje.Models.Entity.Ogrenci", "Ogrenci")
                        .WithOne("Bolum")
                        .HasForeignKey("DersProje.Models.Entity.Bolum", "OgrenciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("DersProje.Models.Entity.OgrenciDers", b =>
                {
                    b.HasOne("DersProje.Models.Entity.Ders", "Dersler")
                        .WithMany("OgrenciDers")
                        .HasForeignKey("DersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DersProje.Models.Entity.Ogrenci", "Ogrenci")
                        .WithMany("OgrenciDers")
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dersler");

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("DersProje.Models.Entity.Ders", b =>
                {
                    b.Navigation("OgrenciDers");
                });

            modelBuilder.Entity("DersProje.Models.Entity.Ogrenci", b =>
                {
                    b.Navigation("Bolum");

                    b.Navigation("OgrenciDers");
                });
#pragma warning restore 612, 618
        }
    }
}
