// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OtobusBileti.Data;

namespace OtobusBileti.Data.Migrations
{
    [DbContext(typeof(OtobusContext))]
    [Migration("20220513132754_mig1")]
    partial class mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.16");

            modelBuilder.Entity("OtobusBileti.Entity.Sehir", b =>
                {
                    b.Property<int>("SehirId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SehirAd")
                        .HasColumnType("TEXT");

                    b.HasKey("SehirId");

                    b.ToTable("Sehirler");
                });

            modelBuilder.Entity("OtobusBileti.Entity.Yol", b =>
                {
                    b.Property<int>("YolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nereden")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nereye")
                        .HasColumnType("TEXT");

                    b.Property<string>("Saat")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tarih")
                        .HasColumnType("TEXT");

                    b.HasKey("YolId");

                    b.ToTable("Yollar");
                });

            modelBuilder.Entity("OtobusBileti.Entity.Yolcu", b =>
                {
                    b.Property<int>("YolcuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .HasColumnType("TEXT");

                    b.Property<int>("Fiyat")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KoltukNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nereden")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nereye")
                        .HasColumnType("TEXT");

                    b.Property<string>("Soyad")
                        .HasColumnType("TEXT");

                    b.Property<int>("YolId")
                        .HasColumnType("INTEGER");

                    b.HasKey("YolcuId");

                    b.HasIndex("YolId");

                    b.ToTable("Yolcular");
                });

            modelBuilder.Entity("OtobusBileti.Entity.Yolcu", b =>
                {
                    b.HasOne("OtobusBileti.Entity.Yol", "Yol")
                        .WithMany("Yolcular")
                        .HasForeignKey("YolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Yol");
                });

            modelBuilder.Entity("OtobusBileti.Entity.Yol", b =>
                {
                    b.Navigation("Yolcular");
                });
#pragma warning restore 612, 618
        }
    }
}
